### ISSUE TITLE
Tuple Index out of range for GEM implementation

### ISSUE THREAD

**Issue by CYHSM** [automl/auto-sklearn#107]
I get an error in the gem.py implementation, line 31

```
E = np.linalg.pinv(np.linalg.cholesky(covj + np.eye(covj.shape[0]) * self.precond).T)

IndexError: tuple index out of range
```

which stops the classification. It happened very randomly, sometimes after 5 minutes of training sometimes after 5 hours, which is a bit annoying because it doesnt return the classifier when this error is thrown.

**Comment by mfeurer** [comment]
Does this happen during the `fit()` method or during the `refit()` method?

**Comment by M-OOC-F** [comment]
I just had a rerun and i happens in the refit method!

**Comment by M-OOC-F** [comment]
Okay it seems that it happens when it tries to use gem preprocessing. I saved the model before the refit and the show Models function displays one where it is used:

```
(0.020000, SimpleClassificationPipeline(configuration={
  'balancing:strategy': 'weighting',
  'classifier:__choice__': 'gaussian_nb',
  'imputation:strategy': 'most_frequent',
  'one_hot_encoding:minimum_fraction': 0.020651585936463983,
  'one_hot_encoding:use_minimum_fraction': 'True',
  'preprocessor:__choice__': 'gem',
  'preprocessor:gem:N': 20,
  'preprocessor:gem:precond': 0.10583929520651719,
  'rescaling:__choice__': 'none'})),
```

and in this case the refit method has an error. Can i just remove the gem from the preprocessors somehow?

**Comment by mfeurer** [comment]
Since this model has a very low weight in the final ensemble, you could just remove it and increase the weight of a different model by 0.02. You can also restrict the preprocessing models with the argument `include_preprocessors`, by passing a list of allowed preprocessors (as shown here: https://github.com/automl/auto-sklearn/issues/70). The list of preprocessors is here: https://github.com/automl/auto-sklearn/tree/master/autosklearn/pipeline/components/feature_preprocessing

We're currently looking for a way to solve the problem in the long run.

**Comment by stokasto** [comment]
That is a strange error, it would entail that covj shape is empty...
Can you print it's shape/give info about the data you are using ?

**Comment by mfeurer** [comment]
GEM is removed from auto-sklearn in the development branch, and will be removed in an upcoming bugfix release; therefore I'm closing this issue.
