### ISSUE TITLE
Successive Halving as an intensification strategy?

### ISSUE THREAD

**Issue by lucasnil** [automl/auto-sklearn#1070]
Hello,

I'm a student doing some experiments on Auto-sklearn.

I was going through some of the Search Examples in the documentation:

https://automl.github.io/auto-sklearn/master/examples/60_search/example_successive_halving.html#sphx-glr-examples-60-search-example-successive-halving-py

I'm a little confused regarding the use of Auto-sklearn with Successive Halving as an intensification strategy for SMAC.

Is this an adaptation or the same as using BOHB? 

Thank you!

**Comment by mfeurer** [comment]
This is an adaption of BOHB with the following differences:
* Instead of HyperBand used in BOHB it uses Successive Halving, which you could abbreviate as BOSH. You can also import and use HyperBand instead of Successive Halving to get the BOHB algorithm.
* Instead of BOHB original implementation using a Parzen Estimator model you'll get a Random Forest model.
Would you like to add this information to the example via a PR so it's clear to the next user?

**Comment by lucasnil** [comment]
Thank you for the reply! I would sure like to add this info to the example.

**Comment by mfeurer** [comment]
Cool, looking forward to your PR. Please let me know if you need some pointers.

**Comment by mfeurer** [comment]
Hey @lucasnil any progress on your side?

**Comment by lucasnil** [comment]
Hello @mfeurer, I'm a bit confused about which file I should edit. Is it [this one](https://github.com/automl/auto-sklearn/blob/master/examples/60_search/example_successive_halving.py)?

**Comment by mfeurer** [comment]
Yes, that's correct. You'd need to update the docstring at the top of the file.

**Comment by mfeurer** [comment]
Closed via #1111
