### ISSUE TITLE
Dummy prediction timeout error

### ISSUE THREAD

**Issue by rd27995** [automl/auto-sklearn#1094]
I get almost the same error message - 

ValueError: Dummy prediction failed with run state StatusType.TIMEOUT and additional output: {'error': 'Timeout', 'configuration_origin': 'DUMMY'}.

After receiving this warning - 

[WARNING] [2021-03-11 11:14:55,702:Client-AutoML(1):faa37853-829d-11eb-be96-002590fc6804] Dataset too large for memory limit 3072MB, reducing number of samples from 3738731 to 105683.

If it is reducing the number of samples automatically, why there is a timeout error?

_Originally posted by @rd27995 in https://github.com/automl/auto-sklearn/issues/800#issuecomment-797045653_

**Comment by mfeurer** [comment]
Hi @rd27995, 

so there are two things happening here:
1. The data is subsampled because it most likely wouldn't fit into memory, leading to a memory error on the dummy prediction.
2. It is still too large to be handled by scikit-learn's dummy classifier/regressor, which is rather weird.

Could you please give some details about the dataset size and upload the log file you get?
