### ISSUE TITLE
Any plans for implementing auto-sklearn for Windows Users in near future?

### ISSUE THREAD

**Issue by zarmeen92** [automl/auto-sklearn#118]

**Comment by mfeurer** [comment]
We do not plan to do so because it would introduce severe maintenance overhead (not necessarily in auto-sklearn, but all projects we depend on). Having said this, we actually never tried whether auto-sklearn (or the underlying libraries [SMAC](https://github.com/automl/SMAC3), [pynisher](https://github.com/sfalkner/pynisher) and [RF](https://bitbucket.org/aadfreiburg/random_forest_run)) actually runs on Windows. If you try to do this, please let us know.

**Comment by zarmeen92** [comment]
Yes I tried to run command pip install auto-sklearn on windows,
Error :  Failed to build pyrfr

![capture](https://cloud.githubusercontent.com/assets/15036417/17804252/1c84a9d0-6614-11e6-86a7-c900f53ea220.PNG)

**Comment by mfeurer** [comment]
Could you please copy-paste the whole output here? I think the actual error message is not visible on that screenshot.

**Comment by zarmeen92** [comment]
![capture](https://cloud.githubusercontent.com/assets/15036417/17809050/555bf01a-662d-11e6-8d03-3178ba537287.PNG)

**Comment by mfeurer** [comment]
This seems to be a known problem: http://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio

**Comment by zarmeen92** [comment]
Thanks I will look into it

**Comment by crawfordcomeaux** [comment]
Successfully installed & ran the demo in Bash on Ubuntu on Windows 10, though there was an error that popped up at the end of the call to fit(). (#120)

**Comment by mfeurer** [comment]
Apparently, it can run on Windows using the Bash shell. 

Also, we figured out that at least the pynisher package won't work under standard Windows.

**Comment by xumx** [comment]
Everything else seems to install fine. pyrfr doesn't install.

**Comment by mfeurer** [comment]
Sorry, we cannot help you on this as no one of us uses Windows for python development. If you find a solution to install auto-sklearn on a pure Windows machine, please let us know.

**Comment by louis925** [comment]
pynisher, which calls python resource library, doesn't works under standard Windows.
