### ISSUE TITLE
resampling_strategy not support sklearn.model_selection.LeaveOneOut?

### ISSUE THREAD

**Issue by husi253** [automl/auto-sklearn#1254]
# Short Question Description
When set `resampling_strategy=sklearn.model_selection.LeaveOneOut`, got error message of "Illegal resampling strategy".

# Code example

```
automl = autosklearn.classification.AutoSklearnClassifier(
	time_left_for_this_task=120,
	n_jobs=10, memory_limit=28000,
	include_estimators=[learner],
	ensemble_size=1,
	resampling_strategy=sklearn.model_selection.LeaveOneOut,
)
```

# Error detail

```
Traceback (most recent call last):
  File "./train.py", line 304, in <module>
    batch_learner_multi_train()
  File "./train.py", line 298, in batch_learner_multi_train
    multi_train(learner)
  File "./train.py", line 269, in multi_train
    train_try(
  File "./train.py", line 221, in train_try
    automl.fit(xTrain, yTrain)
  File "/home/user/miniconda3/envs/myEnv2/lib/python3.8/site-packages/autosklearn/estimators.py", line 941, in fit
    super().fit(
  File "/home/user/miniconda3/envs/myEnv2/lib/python3.8/site-packages/autosklearn/estimators.py", line 340, in fit
    self.automl_.fit(load_models=self.load_models, **kwargs)
  File "/home/user/miniconda3/envs/myEnv2/lib/python3.8/site-packages/autosklearn/automl.py", line 1655, in fit
    return super().fit(
  File "/home/user/miniconda3/envs/myEnv2/lib/python3.8/site-packages/autosklearn/automl.py", line 491, in fit
    raise e
  File "/home/user/miniconda3/envs/myEnv2/lib/python3.8/site-packages/autosklearn/automl.py", line 486, in fit
    self._check_resampling_strategy(
  File "/home/user/miniconda3/envs/myEnv2/lib/python3.8/site-packages/autosklearn/automl.py", line 851, in _check_resampling_strategy
    raise ValueError('Illegal resampling strategy: %s' % self._resampling_strategy)
ValueError: Illegal resampling strategy: <class 'sklearn.model_selection._split.LeaveOneOut'>
```

# Linked issue

* [ Leave-one-out cross-validation #149 ](https://github.com/automl/auto-sklearn/issues/149)

# System Details

* auto-sklearn version: 0.12.6
* Running this on Linux.

**Comment by eddiebergman** [comment]
Hi @husi253,

So I've only tested this one `autosklearn 0.14.0` but from looking at prior version, the logic is the same. 

### Workaround
```python
automl = autosklearn.classification.AutoSklearnClassifier(
	time_left_for_this_task=120,
	n_jobs=10, memory_limit=28000,
	include_estimators=[learner],
	ensemble_size=1,
	resampling_strategy=sklearn.model_selection.KFold(n_splits=len(X_train)),
)
```

### Reason
The first point is that you should pass an instance to `resampling_strategy` and not a class as seen in the [example](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_resampling.html#sphx-glr-examples-40-advanced-example-resampling-py).
```python
automl = autosklearn.classification.AutoSklearnClassifier(
	time_left_for_this_task=120,
	n_jobs=10, memory_limit=28000,
	include_estimators=[learner],
	ensemble_size=1,
	resampling_strategy=sklearn.model_selection.LeaveOneOut(),
)
```

However this will lead to an issue:
```
ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/home/skantify/code/asklearn/issue_pipeline/auto-sklearn/autosklearn/evaluation/__init__.py", line 40, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/home/skantify/code/asklearn/issue_pipeline/auto-sklearn/autosklearn/evaluation/train_evaluator.py", line 1350, in eval_cv\n    evaluator = TrainEvaluator(\n  File "/home/skantify/code/asklearn/issue_pipeline/auto-sklearn/autosklearn/evaluation/train_evaluator.py", line 205, in __init__\n    self.num_cv_folds = self.splitter.get_n_splits(\nTypeError: get_n_splits() missing 1 required positional argument: \'X\'\n', 'error': 'TypeError("get_n_splits() missing 1 required positional argument: \'X\'")', 'configuration_origin': 'DUMMY'}.
```

This issue comes from the fact that for most splitters, `splitter.get_n_splits` has the signature `get_n_splits(X=None, y=None, groups=None)` while specifically for `LeaveOneOut`, the signature is [`get_n_splits(X, y=None, groups=None)`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneOut.html#sklearn.model_selection.LeaveOneOut.get_n_splits) where `X` is non-optional.

However, in the doc of `LeaveOneOut` [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneOut.html#sklearn.model_selection.LeaveOneOut), they state:
> Note: LeaveOneOut() is equivalent to KFold(n_splits=n) and LeavePOut(p=1) where n is the number of samples.

Taking a further look at [`KFold.get_n_splits(...)`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold.get_n_splits) and [`LeavePOut.get_n_splits(...)`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeavePOut.html#sklearn.model_selection.LeavePOut.get_n_splits), the signature for `KFold` is `get_n_splits(X=None, y=None, groups=None)` so that's the option to go for.

In the future this is something we should address, apologies for any confusions.

**Comment by husi253** [comment]
Thank you so much for the explanation! @eddiebergman
