### ISSUE TITLE
[Question] How to get the number of runs executed in SMAC for each pipeline?

### ISSUE THREAD

**Issue by jmren168** [automl/auto-sklearn#1462]
I can use runcount_limit to limit the number of runs in SMAC for each pipeline. 

`automl = AutoSklearnClassifier(
    smac_scenario_args={'runcount_limit': 1000},
)`

Is it possible to get the number of executed runs in SMAC for each pipeline?

Or am I misunderstanding the meaning of runcount_limit?

Any comments are highly appreciated.

**Comment by eddiebergman** [comment]
Hi @jmren168,

It sounds like there's a little bit of confusion, as far as I'm aware, `'runcount_limit'` is how many different pipelines autosklearn will evaluate. In general it will only train and evaluate a pipeline once (`holdout`) or several times (`cross_validation`).

There's not a great way to see how many runs were evaluated but you can use 
```python
clf = AutoSklearnClassifier(...)
clf.fit(X, y)

runhistory = clf.autom_.runhistory_
for runkey, runval in runhistory.data.items():
    print(runkey, runval)
```

You can also get an overview of most of these runs with [`clf.leaderboard(detailed=True, ensemble_only=False)`](https://github.com/automl/auto-sklearn/blob/b2ac331c500ebef7becf372802493a7b235f7cec/autosklearn/estimators.py#L654). I'm linking the code as this directly uses the runhistory to generate the runs.

I hope this answers your questions and gives some insight into things.

Best,
Edde

**Comment by jmren168** [comment]
Hi @eddiebergman ,

Thank you for your kindly reply. I got the meaning of `runcount_limit` from https://github.com/automl/auto-sklearn/issues/428. It says I can use `runcount_limit` to run each pipeline for a certain iteration. But since `runcount_limt` just limits the number of iteration, that's why I want to know how to get the actual iteration for each pipeline.

Following your guideline, I tried to use run_history_. It looks like to show the run history of each config_id (default is 25 configs). `num_run` in run_history seems to record the config_id rather than the number of iterations executed in this config_id. Am I correct?

Besides, here's an example to display the above results. [https://colab.research.google.com/drive/19ugMV_g6iIVpZhY3XyG6nPCitEX4-niK#scrollTo=FR1QLI_q2U4Q](url) I also got confused with `Number of target algorithm runs` and `single best optimization score` in `performance_over_time_`. 

1. Does `Number of target algorithm runs` mean the number of total pipelines executed in this case? 
2. If so, how to explain Auto-Sklearn got single best optimization score at the **27th** iteration since it just trained each pipeline once (therefore totally 24 pipelines)? 

Thanks again.

**Comment by eddiebergman** [comment]
Hi @jmren168,

So there is two main categories, one is *iterative* and the rest are not. Unless you have specified something like "holdout-iterative-fit", check out [`resampling-strategy`](https://automl.github.io/auto-sklearn/master/api.html). I think #428 was a misunderstanding, we do not have that feature. To run a single pipeline more than once is to use a `"cv"` resampling strategy. 

1. In the case of a **non-iterative holdout** resampling strategy, **each pipeline gets evaluated once by SMAC**. It will be evaluated by default with [`resampling_strategy_arguments = { "folds": 5 }`](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_resampling.html#cross-validation).

3. In the case of **iterative** algorithms, what happens when you have specified an `"*iterative*"` kind of `resampling-strategy`, **each pipeline can get evaluated more than once by SMAC**. That is dependent upon SMAC and it's scheduling for which @mfeurer might be able to give a better answer.

Considering you haven't mentioned the "iterative" or "cv" resampling strategy, I will assume you are in case 1 and `runcount_limit` means how many pipelines are evaluated, each being evaluated once.

The `performance_over_time_` data is related to the final ensemble built by autosklearn. This ensemble building is interleaved with pipeline evaluation. Eval a pipeline, build an ensemble, eval another pipeline, build an ensemble, eval a pipeline, ... . The `runcount_limit` and number of ensembles built is **not** in one-to-one correspondence. This explains the difference between the `Number of target algorithm runs` and the `single best optimization score`.

You are also correct that `num_run` is essentially a `config_id`, this is perhaps something we should change to be more reflective of what it is.

I hope this helped answer some questions :)

Best,
Eddie

**Comment by jmren168** [comment]
Hi @eddiebergman,

You answered all of my questions,  and yes, I used default "cv" resampling strategy. So each pipeline is evaluated once. 

Thank you for giving me a very very very detailed discussion of `runcount_limit` :)

Best,
JM

**Comment by eddiebergman** [comment]
Hi @jmren168,

Glad you found it helpful. I was answering this quite early this morning and noticed I managed to miss a section, it was perhaps a little confusing. I've updated the answer to hopefully be more clear! :)

**Comment by jmren168** [comment]
Hi @eddiebergman ,

Thank you to make the answer more clear :)

BTW, I still have some minor questions, and hope you could spend a little bit of time answering these questions.

1. When I used initial **25 configurations** to train autosklearn models, I got **24 target algorithm runs**. Why the latter is not 25? Limited by `per_run_time_limit` and `runcount_limit` rather than initial configurations?
2. From `the single best optimization scores`, how could I know **which pipeline** achieves the best performance? [colab example](https://colab.research.google.com/drive/19ugMV_g6iIVpZhY3XyG6nPCitEX4-niK#scrollTo=FR1QLI_q2U4Q). Additionally, is there a straight way to know the best performance is achieved at which iteration without counting ensemble iterations in?

Thanks again.
JM

**Comment by eddiebergman** [comment]
These initial configurations are just meta-learned configurations that we use to provide some initial points SMAC should evaluate to get some information for it surrogate model. This provides no constraint on the actual running of autosklearn though, just a set of initial configurations to try.

For your second question, part b) no there is not but that would be a useful feature and I have added that as an issue #1470.

The second question part a), you can use the dataframe provided by [`leaderboard()`](https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.leaderboard) to extract all the information you need. However it would be good to have more of a handy solution to this!

For any follow up quesions, please create a new issue :)
