### ISSUE TITLE
Questions about the 'mean_test_score' shown in cv_results_

### ISSUE THREAD

**Issue by wangze09** [automl/auto-sklearn#1466]
Hello everyone!

When I was checking the results of the **'mean_test_score'** followed by the command **'model.cv_results_'** , I found that they seemed to be the mean cv scores of the **single model** trained during the search. I just wondered if there was a method to show the mean cv scores of the **final ensembled model**.

Thank you for your time in advance!

**Comment by eddiebergman** [comment]
Hi @wangze09,

Our ensembling method is actually not done in a cross-validation fashion, it's instead done using a greedy-search algorithim and is done continuously as new models get evaluated. Check out this example to learn some [more](https://automl.github.io/auto-sklearn/master/examples/40_advanced/example_pandas_train_test.html#sphx-glr-examples-40-advanced-example-pandas-train-test-py).

The reason for this is evaluating all possible ensembles in a CV search would be too expensive, we would have to spend a large majority of time just evaluating ensembles instead of finding more suitable pipelines. Perhaps @mfeurer can provide more as to why this greedy-method was chosen over others?

You can also check out a bit about ensembling in the manual [here](https://automl.github.io/auto-sklearn/master/manual.html#ensembling), if you havn't seen it already.

Best,
Eddie

**Comment by mfeurer** [comment]
Hi,

@wangze09 what you're looking for is called "ensemble_optimization_score" in the example linked by @eddiebergman. The performance of the single best model is called "single_best_optimization_score". These scores available in case of both holdout and cv.

WRT the ensemble method: at the time of writing we found Ensemble Selection to produce the most reliable results in the AutoML setting.

**Comment by wangze09** [comment]
Hi!
@mfeurer @eddiebergman 
Thanks a lot for answering my question, I got that!
Enjoy your time!
