### ISSUE TITLE
[Question] Does per_run_time_limit only include the time used to fit a machine learning algorithm?

### ISSUE THREAD

**Issue by jmren168** [automl/auto-sklearn#1524]
Hi, 

From the api website (https://automl.github.io/auto-sklearn/master/api.html), it says **per_run_time_limit** means _time limit for a single call to the machine learning model_, and _model fitting will be terminated if the machine learning algorithm runs over the time limit_.

As far as I know, training a configuration in auto-sklearn includes three main stages: machine learning model fitting, surrogate model building, and acquisition function maximization. **Is it possible the training is terminated in surrogate model building or acquisition function maximization?** If so, **per_run_time_limit** should also include the time used to build surrogate model and maximize acquisition function. Am I correct? Thank you for your response in advance.

**Comment by mfeurer** [comment]
Hi,
this time applies solely to the stage "machine learning model fitting". We apply this limit because we have no idea how ling these runs will take (think of applying a support vector machine to a large dataset). In contrast, the other two stages or rather short and we have an idea about how long they take, so we do not need to limit them.

**Comment by jmren168** [comment]
Hi @mfeurer,

Thank you for the response again. I got more insights of auto-sklearn :)
