### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by bmmalone** [automl/auto-sklearn#166]
I am using the 0.0.2 development branch (with python 3.5.1) in order to use AutoSklearnRegressor. Everything seems to be going fine with the quality of the models. However, "top" shows that during training, the process is using, essentially, all of the cores it can see. I am not using "shared_mode".

I am running this on a shared cluster, so I'd prefer to explicitly limit the number of available CPUs for training. Is it possible to pass an "njobs"-like parameter somehow? or something similar.

Here is a minimal example which reproduces this behavior:

```
from autosklearn.regression import AutoSklearnRegressor
import sklearn.datasets

data = sklearn.datasets.load_boston()

X = data.data
y = data.target

regressor = AutoSklearnRegressor(time_left_for_this_task=600)
regressor.fit(X, y)
```

**Comment by mfeurer** [comment]
I can somewhat reproduce that, although not to the extend you're reporting this issue. I assume this issue arises because of the underlying BLAS library. Could you please describe how you installed numpy? In case you downloaded numpy via `pip install numpy`, it uses all cores by default if possible. Some of the models in auto-sklearn can make use of that, that's why it's not constantly using all CPUs. Executing `export OPENBLAS_NUM_THREADS=1` in your shell prior to the execution of auto-sklearn should prevent that.

Besides that, auto-sklearn uses two cores by default. One is for building machine learning models, the other for building ensembles. If you alter the parallel example such that it only runs a single worker job at a time and you build the ensemble afterwards, you get the desired behaviour.

**Comment by bmmalone** [comment]
Thanks for the quick response, Matthias. I did install numpy with pip (linking to openblas), and setting the threads by exporting `OPENBLAS_NUM_THREADS` seems to ensure the number of BLAS threads is limited. I know that's not a part of auto-sklearn, so I really appreciate you pointing that out.

A very-related question... is there a good way to set the number of threads for blas once the python interpreter is started? I found this [SO](http://stackoverflow.com/questions/29559338/set-max-number-of-threads-at-runtime-on-numpy-openblas) thread, but is there anything a bit more light-weight (or now-builtin)?

I know this isn't directly related to auto-sklearn, but it seems related to this issue; and an "njobs" option would be really nice :) Any additional insight would be very appreciated.

P.S. The actual issue is resolved and can be closed; I wasn't sure the best way to bring up the follow-up question.

**Comment by mfeurer** [comment]
You're welcome. Unfortunately, I can't answer your follow-up question. At least in the context of auto-sklearn it would not be desirable to use more than one core to tune the machine learning algorithms since some of them do not support any form of multithreading/multiprocessing. In that context I advise you to run auto-sklearn in parallel as showcased in the examples.
