### ISSUE TITLE
Another pyrfr fail

### ISSUE THREAD

**Issue by TKlerx** [automl/auto-sklearn#168]
Hi,

even though there is already #101 I opened this new issue because (I guess) the problem is different:

pyrfr fails with ImportError: ...pyrfr/regression.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

I guess the issue is related to the gcc compiler.
I tried this on a fresh Fedora 24 VM with gcc6 and anaconda (python3).

Doing the same on a fresh Ubuntu 14.04 with gcc 4.8 and anaconda (python3), it works without an error.

**Comment by mfeurer** [comment]
Thanks for reporting this. @sfalkner could you please have a brief look at this issue?

**Comment by sfalkner** [comment]
Hi,
the problem is anaconda. You would have to build pyrfr (Our own random forest implementation in C++) with the same gcc version that anaconda was build. I wouldn't be surprised if gcc on ubuntu is compatible to the one used for anaconda. But I don't know how to do that, although it should be possible.
It should work if you use the systems python version and install the necessary dependencies using your package manager (dpkg on Fedora, I guess).
Best,
Stefan

**Comment by TKlerx** [comment]
Hi,
thanks for the quick replies and the clarification.
I'll give it a try.

Best,
Timo
