### ISSUE TITLE
Crossvalidation for Regression throws warning

### ISSUE THREAD

**Issue by TKlerx** [automl/auto-sklearn#182]
When using AutoSkLearnRegressor with crossvalidation, the following warning is thrown:

python3.5/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=5.
  % (min_labels, self.n_folds)), Warning)

I am surprised that the warning comes from directly from python, but usually sklearn CV does not throw a warning for regression tasks,

**Comment by mfeurer** [comment]
Thanks for reporting this. The issue here is that we don't pass a flag whether we do classification or regression to the CV splitting module in auto-sklearn, see the code [here](https://github.com/automl/auto-sklearn/blob/master/autosklearn/evaluation/resampling.py#L86). This warning shouldn't be an issue in practice. Nevertheless, would you like to contribute to auto-sklearn by fixing this issue?

**Comment by mfeurer** [comment]
I just checked this issue, and it is no longer present in the latest bugfix release 0.1.3.
