### ISSUE TITLE
smac 0.2.1 uses static typing

### ISSUE THREAD

**Issue by elibol** [automl/auto-sklearn#201]
smac 0.2.1 uses static typing, which breaks auto-sklearn on python 2.7. We currently have to manually install smac 0.1.0 to use this package.

**Comment by mfeurer** [comment]
auto-sklearn is developed mostly as a research project. Given that all developers are researchers at a university, we can't afford the time it takes to maintain backwards compability with older python versions.

Since I advise you to not use smac 0.1.0 since it contains several (now fixed) bugs, I'm asking myself what requires you to use python2.7. In most cases you should be able to set up a python3 environment with either the system python distribution (works on Linux) or Anaconda (works also on OSX).

**Comment by elibol** [comment]
Thanks for the quick response. We're using your package on a hadoop cluster with pyspark. Although we understand why you no longer officially support python 2.7, right now the cost of switching to python 3 for us are greater than the benefits. We're fixing our version of auto-sklearn to 0.1.0 to complete our experiments, which appears to be working.
