### ISSUE TITLE
Theory - Code question

### ISSUE THREAD

**Issue by Aaaaaaare** [automl/auto-sklearn#237]
I have a question regrading the theoretical approach (and it is also related with the code). This is not an error/problem post.

My question is: every time a hyperparameter configuration is selected to be tested during the training, with the pipeline structure you can compute the fit function of that configuration (the fit function of the classifier/regressor selected in such config) [Here im talking about the `fit_estimator(self, X, y, **fit_params)` function of BasePipeline, in autosklearn/pipeline/base.py]. But the number of instances to be used to train the classifier/regressor is always the same in every cycle (for a given dataset). Where and how is that number of instances computed? Why is it fixed? (for example, for boston dataset, following the example_regression.py, the number of instances is always 253). And also, I have notice that the number of features of each instance varies a lot (from 2 to 9000), which I don't fully understand.

Thank you for all your help, and sorry if this question is out of place.

**Comment by mfeurer** [comment]
The number of instances is fixed by the evaluation strategy. In the case of holdout, this means that 67% of the data passed to `AutoSklearnClassifier.fit(X, y)` are used for training, the rest as a holdout set to compute the validation error to optimize. The number of features to `fit_estimator` can change because the preprocessing algorithm changes the number of features. You could check that preprocessors such as features selection or pca actually reduce the number of features, while kernel approximations like the nyström sampler or random kitchen sinks actually increase the number of features.

**Comment by mfeurer** [comment]
@Aaaaaaare can this be closed?

**Comment by Aaaaaaare** [comment]
Yes =)! Your answer was all I needed, thank you very much! I was sure i replied to you, it seems I didn't. Sorry, I should have double checked.

**Comment by mfeurer** [comment]
No problem :)
