### ISSUE TITLE
Document dependency on swig on the installation instructions

### ISSUE THREAD

**Issue by rcalsaverini** [automl/auto-sklearn#277]
Hello,
I had some trouble installing auto-sklearn and realized that the problem was that pyrfr depends on swig, and it actually requires swig3.0 and not swig2.0. 

Perhaps a note in the installation instructions recommending Ubuntu users to run `apt-get install swig` and other distros to install swig 3.0.8 before installing the python dependecies would be nice.

**Comment by rcalsaverini** [comment]
I found the relevant part of the documentation and added a pull request.

**Comment by rcalsaverini** [comment]
Yep. SWIG is correctly mentioned in the development branch documentation. I just added a reference to the specific version pyrfr depends on (which is 3.0 or later) instructions on how to install it on ubuntu (since there are multiple SWIG packages on Ubuntu and this can cause confusion).

**Comment by mfeurer** [comment]
Okay, the actual issue is that the master doesn't specify a dependency on `pyrfr==0.2.0`, but only `pyrfr`. pip will then try to install `pyrfr==0.4.0`, which needs SWIG and won't work with the current auto-sklearn on pypi. Please install the latest version of auto-sklearn from the development branch as well.

Also, thanks a lot for providing a pull request.
