### ISSUE TITLE
Shouldn't the roc_auc scorer set needs_proba=True ?

### ISSUE THREAD

**Issue by vicentealencar** [automl/auto-sklearn#329]
So, as far as I know, in order to correctly calculate the AUC score, one needs to call sklearn's `roc_auc_score` function using the output of `predict_proba` as the `y_pred` output:

```python
from sklearn.metrics import roc_curve, auc, roc_auc_score

# say we have previously trained a classifier clf and split x_test and Y_test for validation purposes
fpr, tpr, thresholds = roc_curve(Y_test, clf.predict_proba(x_test)[:,1])
auc(fpr, tpr) #outputs the AUC. This is equivalent to calling roc_auc_score(Y_test, clf.predict_proba(x_test)[:,1])
```

I was browsing through the `autosklearn.metrics` module in order to get a better idea of how it works and I have noticed that the `roc_auc` scorer is currently using the `needs_proba=False` default setting in its definition:

```python
roc_auc = make_scorer('roc_auc', sklearn.metrics.roc_auc_score,
greater_is_better=True, needs_threshold=True)
```
So, if I got this correctly, the scorer above will not correctly calculate the AUC, since it is calling `predict`, which already established the decision boundary. Am I missing something?

**Comment by mfeurer** [comment]
I must admit that this is somehow confusing and I had to look this up myself. Auto-sklearn uses it's own declaration of [`make_scorer`](https://github.com/automl/auto-sklearn/blob/master/autosklearn/metrics/__init__.py#L136) and [`_ThresholdScorer`](https://github.com/automl/auto-sklearn/blob/master/autosklearn/metrics/__init__.py#L100). The main difference to scikit-learn is that each scorer in Auto-sklearn already receives the outputs of `predict_proba` because this way the overall workflow is easier to implement for us. It is then handled in the same way as scikit-learn handles the predictions (see [here](https://github.com/scikit-learn/scikit-learn/blob/ab93d657eb4268ac20c4db01c48065b5a1bfe80d/sklearn/metrics/scorer.py#L184)). I hope this clarifies.

**Comment by vicentealencar** [comment]
Yep, this makes it a lot clearer. Sorry for the confusion. Closing the issue.
