### ISSUE TITLE
Settings for short test run?

### ISSUE THREAD

**Issue by ThunderShiviah** [automl/auto-sklearn#34]
Are there automl settings that would bring the training time (on the digits set for example )to something negligible (<10 minutes) for quick experimentation and code integration tests? 

I'm currently experimenting with putting automl in my code, but the ~1 hour training time is a huge bottleneck. A setting for a quick throwaway run would be really helpful.

**Comment by hmendozap** [comment]
When you create your classifier there is the option (default=3600)
````
time_left_for_this_task= TIME-IN-SECONDS
````
But be aware, that this also reduces the time of each smac run

**Comment by mfeurer** [comment]
There is another option called `per_run_time_limit` which controls the execution time of a single ML run. Because digits is rather small, you can try 15 seconds here, and 60 seconds for the overall time limit that @hmendozap mentioned. To make it even faster, you can change the digits dataset to the iris dataset, which also comes bundled with scikit-learn (change `load_digits()` to `load_iris()`).

**Comment by ThunderShiviah** [comment]
Awesome suggestions! I'll try those out!
