### ISSUE TITLE
SVM: do we need the polynomial kernel

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#445]
in initial experiments it is way slower than the RBF kernel.

**Comment by VladimirGl** [comment]
It also sometimes causes hangs for me then use ask on multithread mode (so I have separate model fitters and one ensembler).
So it was killed by time limits inside models fitters, but then I call refit on ensembler thread on whole data on, or on different folds (if use external cv) it never stops (may be related to some data scaling issues, not sure). I just set max number of iterations to couple of thousands instead of -1 to avoid this.

**Comment by mfeurer** [comment]
Another related question: do we need to apply calibration via Platt Scaling to SVMs? [Getting the most out of ensemble selection](https://www.researchgate.net/publication/220766367_Getting_the_Most_Out_of_Ensemble_Selection) suggests that this is not necessary, so the time required to calibrate the SVM might rather be spent on searching for better hyperparameters.

**Comment by mfeurer** [comment]
Closing, see #1314 for the reasoning.
