### ISSUE TITLE
How about the preformance compared to auto-weka 2.0?

### ISSUE THREAD

**Issue by szldmgy** [automl/auto-sklearn#463]
We know that auto-sklearn has expoited some techniques from auto-weka, and been further improved by meta-learning and ensemble. Later, auto-weka has released its 2.0 version (http://www.cs.ubc.ca/labs/beta/Projects/autoweka/), how about their performance compared to each other?

**Comment by mfeurer** [comment]
According to the paper, these are the changes:

1. First, we now support regression algorithms, expanding Auto-WEKA beyond its previous focus on classi cation (starred entries in Fig. 1). 
2. Second, we now support the optimization of all performance metrics WEKA supports. 
3. Third, we now natively support parallel runs (on a single machine) to  nd good con gurations faster and save the N best configurations of each run instead of just the single best. 
4. Fourth, Auto-WEKA 2.0 is now fully integrated with WEKA

Therefore I suggest the performance is comparable to Auto-WEKA and the results in [the auto-sklearn paper](https://papers.nips.cc/paper/5872-efficient-and-robust-automated-machine-learning.pdf) should be comparable.

@larskotthoff what do you think?

**Comment by larskotthoff** [comment]
@mfeurer I agree completely. The core of Auto-WEKA hasn't changed, so I wouldn't expect performance to be different. I don't think there's a need for a new performance comparison.
