### ISSUE TITLE
how to find the best model

### ISSUE THREAD

**Issue by fdas3213** [automl/auto-sklearn#490]
Hi, I am new to auto-sklearn. I loaded iris dataset from sklearn.datasets and did a simple test using autosklearn. Below is my code:

```
x,y = datasets.load_iris()['data'], datasets.load_iris()['target']
automl = autosklearn.classification.AutoSklearnClassifier(emsemble_size = 1,initial_configuration_via_metalearning = 0)
automl.fit(x,y)
```
after running for more than 1hr, I tried to use
`automl.show_models()
`to find the best model, and here is the result I got:
```
[(1.000000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'categorical_encoding:__choice__': 'one_hot_encoding', 'classifier:__choice__': 'gaussian_nb', 'imputation:strategy': 'most_frequent', 'preprocessor:__choice__': 'polynomial', 'rescaling:__choice__': 'standardize', 'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'False', 'preprocessor:polynomial:degree': 3, 'preprocessor:polynomial:include_bias': 'True', 'preprocessor:polynomial:interaction_only': 'False'},\ndataset_properties={\n  'task': 2,\n  'sparse': False,\n  'multilabel': False,\n  'multiclass': True,\n  'target_type': 'classification',\n  'signed': False})),\n]
```
So does this mean that my best classifier is "gaussian_nb"?
But when I try to use
`automl.predict(x)`, I found that this cannot outperform `SVC()`, so could anyone help me clarify this? 
Thank you!

**Comment by mfeurer** [comment]
The model(s) shown by `automl.show_models()` is/are models in a final ensemble constructing by Auto-sklearn. 

During the 1h Auto-sklearn optimizes the hyperparameters of several scikit-learn algorithms. In order to quantify the quality, it evaluates those algorithms on a part of the data you provide as training data. As you're using the rather small iris data set, it can happen that within 1h you overfit to the small validation data set. For this particular example I suggest that you use cross-validation as described in this example: http://automl.github.io/auto-sklearn/dev/examples/example_crossvalidation.html#sphx-glr-examples-example-crossvalidation-py. In general, Auto-sklearn works best if you have a reasonable amount of data (let's say >= 2000).

**Comment by fdas3213** [comment]
Hi @mfeurer , thanks for the explanation. What I am trying to find is a single best model, like SVM, logistic regression, etc. So do you know any way for me to find that?

**Comment by mfeurer** [comment]
So you try to find the best model class/family. The definition of *best* depends on the setting. Given the information I have, you should have a look at the cross-validation example and use the final model. If you provide further details on your use case I might be able to give you a different answer.

**Comment by fdas3213** [comment]
@mfeurer Thank you. I guess cross-validation example is what I am looking for.

**Comment by ballcap231** [comment]
@mfeurer Is there an easier way to read the best model produced by `automl_show_models()`? The string returned from it is rather huge and not human-friendly to read.
