### ISSUE TITLE
incremental or partial_fit

### ISSUE THREAD

**Issue by bytearchive** [automl/auto-sklearn#696]
I have very large dataset a csv file of 900GB.

Can I use auto-sklean with it using ```partial_fit``` or any incremental training?

I know that sk-learn have many ```partial_fit``` methods, are any of them exposed in ```autosklearn.classification.AutoSklearnClassifier``` API

**Comment by mfeurer** [comment]
Unfortunately, Auto-sklearn does not support incremental or partial training of datasets that do not fit into memory. We're not exposing any `partial_fit` methods of the scikit-learn classifiers. Even then Auto-sklearn would most likely not work on such data because one central assumption in the code is that the full dataset is passed when calling `AutoSklearnClassifier.fit()`.

**Comment by mapmeld** [comment]
Hi @mfeurer - on my repo I'm exploring how partial_fit / incremental learning might be possible ( https://github.com/Georeactor/auto-sklearn ). Interested in your thoughts on this!

Current setup:
- ```autosklearn.classification.AutoSklearnClassifier(incremental_learning=True)``` to activate incremental learning
- raising an error if ```fit``` or ```partial_fit``` called in the wrong context
- ```incremental_learning=True``` gets passed to ```dataset_properties```, to limit which classifiers we select (each has ```iterative_fit``` already in Auto-Sklearn components)

Going forward, I would allow the user to set the range and categories of their columns instead of detecting them in the first dataset. Then - I need to dig deeper into how the separate processes and pipelines work - when someone calls ```partial_fit``` again, this would either add data to the current pipeline, or remember some data about the best alternative pipelines to give them another try.
