### ISSUE TITLE
Is it possible to remove a portion dataset from the 140 used for metalearning? 

### ISSUE THREAD

**Issue by hamaxostichus** [automl/auto-sklearn#724]
Hello I am trying to substitute 10 out of the 140 datasets used for metalearning with some datasets of my own selection. I have figured out how to integrate more datasets but is I'm wondering if there is a way to remove some datasets from the Autosklearn? For example maybe regulate the id of datasets Autosklearn would look at in the metalearning procedure. Would you please provide some advice or instructions?
Many thanks in advance!

**Comment by mfeurer** [comment]
We currently only allow removing a single dataset from the metadata. This happens if one of the metadatasets has the same name as the dataset name given in `fit()`.

If you require removing more datasets, you could have a look at https://github.com/automl/auto-sklearn/blob/master/scripts/2015_nips_paper/run/remove_dataset_from_metadata.py and extend it to your needs.
