### ISSUE TITLE
where does auto-sklearn log to by default?

### ISSUE THREAD

**Issue by ezeeetm** [automl/auto-sklearn#836]
Using auto-sklearn on Ubuntu, its working great, but not seeing where it logs to during execution?

**Comment by mfeurer** [comment]
In the examples, for example [the holdout example](https://automl.github.io/auto-sklearn/master/examples/example_holdout.html#sphx-glr-examples-example-holdout-py), there's an argument called `tmp_folder` where the logfile is written to. If you set this argument, the tmp folder will be at the given location, otherwise, auto-sklearn will use [python's tempfile](https://docs.python.org/3/library/tempfile.html) functionality to create a temporary directory.

**Comment by mfeurer** [comment]
Closing as this will be covered in an upcoming FAQ.
