### ISSUE TITLE
docker can run successfully ,but can't run example_regression.py in this docker

### ISSUE THREAD

**Issue by wdc-yan** [automl/auto-sklearn#938]
## Describe the bug ##
docker can run successfully ,but can't run example_regression.py in this docker

## To Reproduce ##
1. build and enter the docker
2. run python3 example_regression.py

## Expected behavior ##
Successfully run

## Actual behavior, stacktrace or logfile ##
```
root@e027b67693e6:/ex# python3 example_regression.py
/usr/local/lib/python3.8/dist-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
[WARNING] [2020-09-02 02:37:31,531:AutoMLSMBO(1)::boston] Could not find meta-data directory /usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/files/r2_regression_dense
Segmentation fault
```

## Environment and installation: ##

same as dockerfile 

* OS
* Is your installation in a virtual environment or conda environment? :same as dockerfile
* Python version :same as dockerfile
* Auto-sklearn version :same as dockerfile

**Comment by mfeurer** [comment]
Hey there,

I'm afraid that this is due to an old docker image. Could you please let us know from where and when you retrieved it?

We have just pushed new docker images to dockerhub, and you can get the latest one with `docker pull mfeurer/auto-sklearn:master`. I tested that the example runs in the docker image. Please try the new image and re-open the issue if it doesn't work with that image.
